# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  push:
    branches:
      - "master"
      - "main"
  workflow_dispatch:

# List of jobs
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
